
use super::*;

// ------------------------------------------------------------------------------------------------
// InstDesc table
// ------------------------------------------------------------------------------------------------

pub fn lookup_desc(opcode: u8) -> &'static InstDesc {
	INST_DESC_TABLE.get(&opcode).unwrap_or(&&OP_INVALID)
}

lazy_static! {
	static ref INST_DESC_TABLE: HashMap<u8, &'static InstDesc> = {
		let mut m = HashMap::new();
		for o in INST_DESCS { m.insert(o.opcode, o); }
		m
	};
}

const OP_INVALID: InstDesc = InstDesc::new(0xFF, MetaOp::UNK, AddrMode::IMP, false, None);

const INST_DESCS: &[InstDesc] = &[
	InstDesc::new(0x00, MetaOp::BRK,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x01, MetaOp::ORA,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x05, MetaOp::ORA,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x06, MetaOp::ASL,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(0x08, MetaOp::PHP,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x09, MetaOp::ORA,  AddrMode::IMM, false, None                   ),
	InstDesc::new(0x0A, MetaOp::ASLA, AddrMode::IMP, false, None                   ),
	InstDesc::new(0x0D, MetaOp::ORA,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x0E, MetaOp::ASL,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(0x10, MetaOp::BPL,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(0x11, MetaOp::ORA,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x15, MetaOp::ORA,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x16, MetaOp::ASL,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x18, MetaOp::CLC,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x19, MetaOp::ORA,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(0x1D, MetaOp::ORA,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x1E, MetaOp::ASL,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x20, MetaOp::JSR,  AddrMode::LAB, true,  Some(MemAccess::Target)),
	InstDesc::new(0x21, MetaOp::AND,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x24, MetaOp::BIT,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x25, MetaOp::AND,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x26, MetaOp::ROL,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(0x28, MetaOp::PLP,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x29, MetaOp::AND,  AddrMode::IMM, false, None                   ),
	InstDesc::new(0x2A, MetaOp::ROLA, AddrMode::IMP, false, None                   ),
	InstDesc::new(0x2C, MetaOp::BIT,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x2D, MetaOp::AND,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x2E, MetaOp::ROL,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(0x30, MetaOp::BMI,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(0x31, MetaOp::AND,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x35, MetaOp::AND,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x36, MetaOp::ROL,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x38, MetaOp::SEC,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x39, MetaOp::AND,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(0x3D, MetaOp::AND,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x3E, MetaOp::ROL,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x40, MetaOp::RTI,  AddrMode::IMP, true , None                   ),
	InstDesc::new(0x41, MetaOp::EOR,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x45, MetaOp::EOR,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x46, MetaOp::LSR,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(0x48, MetaOp::PHA,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x49, MetaOp::EOR,  AddrMode::IMM, false, None                   ),
	InstDesc::new(0x4A, MetaOp::LSRA, AddrMode::IMP, false, None                   ),
	InstDesc::new(0x4C, MetaOp::JMP,  AddrMode::LAB, true,  Some(MemAccess::Target)),
	InstDesc::new(0x4D, MetaOp::EOR,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x4E, MetaOp::LSR,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(0x50, MetaOp::BVC,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(0x51, MetaOp::EOR,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x55, MetaOp::EOR,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x56, MetaOp::LSR,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x58, MetaOp::CLI,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x59, MetaOp::EOR,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(0x5D, MetaOp::EOR,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x5E, MetaOp::LSR,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x60, MetaOp::RTS,  AddrMode::IMP, true , None                   ),
	InstDesc::new(0x61, MetaOp::ADC,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x65, MetaOp::ADC,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x66, MetaOp::ROR,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(0x68, MetaOp::PLA,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x69, MetaOp::ADC,  AddrMode::IMM, false, None                   ),
	InstDesc::new(0x6A, MetaOp::RORA, AddrMode::IMP, false, None                   ),
	InstDesc::new(0x6C, MetaOp::JMP,  AddrMode::IND, true,  Some(MemAccess::Read)  ),
	InstDesc::new(0x6D, MetaOp::ADC,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x6E, MetaOp::ROR,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(0x70, MetaOp::BVS,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(0x71, MetaOp::ADC,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x75, MetaOp::ADC,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x76, MetaOp::ROR,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x78, MetaOp::SEI,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x79, MetaOp::ADC,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(0x7D, MetaOp::ADC,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x7E, MetaOp::ROR,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x81, MetaOp::STA,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x84, MetaOp::STY,  AddrMode::ZPG, false, Some(MemAccess::Write) ),
	InstDesc::new(0x85, MetaOp::STA,  AddrMode::ZPG, false, Some(MemAccess::Write) ),
	InstDesc::new(0x86, MetaOp::STX,  AddrMode::ZPG, false, Some(MemAccess::Write) ),
	InstDesc::new(0x88, MetaOp::DEY,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x8A, MetaOp::TXA,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x8C, MetaOp::STY,  AddrMode::ABS, false, Some(MemAccess::Write) ),
	InstDesc::new(0x8D, MetaOp::STA,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x8E, MetaOp::STX,  AddrMode::ABS, false, Some(MemAccess::Write) ),
	InstDesc::new(0x90, MetaOp::BCC,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(0x91, MetaOp::STA,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(0x94, MetaOp::STY,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x95, MetaOp::STA,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0x96, MetaOp::STX,  AddrMode::ZPY, false, Some(MemAccess::Offset)),
	InstDesc::new(0x98, MetaOp::TYA,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x99, MetaOp::STA,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(0x9A, MetaOp::TXS,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0x9D, MetaOp::STA,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xA0, MetaOp::LDYI, AddrMode::IMM, false, None                   ),
	InstDesc::new(0xA1, MetaOp::LDA,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xA2, MetaOp::LDXI, AddrMode::IMM, false, None                   ),
	InstDesc::new(0xA4, MetaOp::LDY,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xA5, MetaOp::LDA,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xA6, MetaOp::LDX,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xA8, MetaOp::TAY,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0xA9, MetaOp::LDAI, AddrMode::IMM, false, None                   ),
	InstDesc::new(0xAA, MetaOp::TAX,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0xAC, MetaOp::LDY,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xAD, MetaOp::LDA,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xAE, MetaOp::LDX,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xB0, MetaOp::BCS,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(0xB1, MetaOp::LDA,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xB4, MetaOp::LDY,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xB5, MetaOp::LDA,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xB6, MetaOp::LDX,  AddrMode::ZPY, false, Some(MemAccess::Offset)),
	InstDesc::new(0xB8, MetaOp::CLV,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0xB9, MetaOp::LDA,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(0xBA, MetaOp::TSX,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0xBC, MetaOp::LDY,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xBD, MetaOp::LDA,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xBE, MetaOp::LDX,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(0xC0, MetaOp::CPY,  AddrMode::IMM, false, None                   ),
	InstDesc::new(0xC1, MetaOp::CMP,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xC4, MetaOp::CPY,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xC5, MetaOp::CMP,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xC6, MetaOp::DEC,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(0xC8, MetaOp::INY,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0xC9, MetaOp::CMP,  AddrMode::IMM, false, None                   ),
	InstDesc::new(0xCA, MetaOp::DEX,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0xCC, MetaOp::CPY,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xCD, MetaOp::CMP,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xCE, MetaOp::DEC,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(0xD0, MetaOp::BNE,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(0xD1, MetaOp::CMP,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xD5, MetaOp::CMP,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xD6, MetaOp::DEC,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xD8, MetaOp::CLD,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0xD9, MetaOp::CMP,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(0xDD, MetaOp::CMP,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xDE, MetaOp::DEC,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xE0, MetaOp::CPX,  AddrMode::IMM, false, None                   ),
	InstDesc::new(0xE1, MetaOp::SBC,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xE4, MetaOp::CPX,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xE5, MetaOp::SBC,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xE6, MetaOp::INC,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(0xE8, MetaOp::INX,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0xE9, MetaOp::SBC,  AddrMode::IMM, false, None                   ),
	InstDesc::new(0xEA, MetaOp::NOP,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0xEC, MetaOp::CPX,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xED, MetaOp::SBC,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xEE, MetaOp::INC,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(0xF0, MetaOp::BEQ,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(0xF1, MetaOp::SBC,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(0xF5, MetaOp::SBC,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xF6, MetaOp::INC,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xF8, MetaOp::SED,  AddrMode::IMP, false, None                   ),
	InstDesc::new(0xF9, MetaOp::SBC,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(0xFD, MetaOp::SBC,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(0xFE, MetaOp::INC,  AddrMode::ABX, false, Some(MemAccess::Offset)),
];