
use super::*;

// ------------------------------------------------------------------------------------------------
// InstDesc table
// ------------------------------------------------------------------------------------------------

pub fn lookup_desc(opcode: u8) -> &'static InstDesc {
	INST_DESC_TABLE.get(&opcode).unwrap_or(&&OP_INVALID)
}

lazy_static! {
	static ref INST_DESC_TABLE: HashMap<u8, &'static InstDesc> = {
		let mut m = HashMap::new();
		for o in INST_DESCS { m.insert(o.opcode as u8, o); }
		m
	};
}

const OP_INVALID: InstDesc = InstDesc::new(
	Opcode::INVALID,                MetaOp::UNK, AddrMode::IMP, false, None);

const INST_DESCS: &[InstDesc] = &[
	InstDesc::new(Opcode::BRK_IMP,  MetaOp::BRK,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::ORA_IZX,  MetaOp::ORA,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::ORA_ZPG,  MetaOp::ORA,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::ASL_ZPG,  MetaOp::ASL,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(Opcode::PHP_IMP,  MetaOp::PHP,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::ORA_IMM,  MetaOp::ORA,  AddrMode::IMM, false, None                   ),
	InstDesc::new(Opcode::ASL_IMP,  MetaOp::ASLA, AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::ORA_ABS,  MetaOp::ORA,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::ASL_ABS,  MetaOp::ASL,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::BPL_REL,  MetaOp::BPL,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(Opcode::ORA_IZY,  MetaOp::ORA,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::ORA_ZPX,  MetaOp::ORA,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::ASL_ZPX,  MetaOp::ASL,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::CLC_IMP,  MetaOp::CLC,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::ORA_ABY,  MetaOp::ORA,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::ORA_ABX,  MetaOp::ORA,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::ASL_ABX,  MetaOp::ASL,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::JSR_LAB,  MetaOp::JSR,  AddrMode::LAB, true,  Some(MemAccess::Target)),
	InstDesc::new(Opcode::AND_IZX,  MetaOp::AND,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::BIT_ZPG,  MetaOp::BIT,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::AND_ZPG,  MetaOp::AND,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::ROL_ZPG,  MetaOp::ROL,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(Opcode::PLP_IMP,  MetaOp::PLP,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::AND_IMM,  MetaOp::AND,  AddrMode::IMM, false, None                   ),
	InstDesc::new(Opcode::ROL_IMP,  MetaOp::ROLA, AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::BIT_ABS,  MetaOp::BIT,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::AND_ABS,  MetaOp::AND,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::ROL_ABS,  MetaOp::ROL,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::BMI_REL,  MetaOp::BMI,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(Opcode::AND_IZY,  MetaOp::AND,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::AND_ZPX,  MetaOp::AND,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::ROL_ZPX,  MetaOp::ROL,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::SEC_IMP,  MetaOp::SEC,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::AND_ABY,  MetaOp::AND,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::AND_ABX,  MetaOp::AND,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::ROL_ABX,  MetaOp::ROL,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::RTI_IMP,  MetaOp::RTI,  AddrMode::IMP, true , None                   ),
	InstDesc::new(Opcode::EOR_IZX,  MetaOp::EOR,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::EOR_ZPG,  MetaOp::EOR,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::LSR_ZPG,  MetaOp::LSR,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(Opcode::PHA_IMP,  MetaOp::PHA,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::EOR_IMM,  MetaOp::EOR,  AddrMode::IMM, false, None                   ),
	InstDesc::new(Opcode::LSR_IMP,  MetaOp::LSRA, AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::JMP_LAB,  MetaOp::JMP,  AddrMode::LAB, true,  Some(MemAccess::Target)),
	InstDesc::new(Opcode::EOR_ABS,  MetaOp::EOR,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::LSR_ABS,  MetaOp::LSR,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::BVC_REL,  MetaOp::BVC,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(Opcode::EOR_IZY,  MetaOp::EOR,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::EOR_ZPX,  MetaOp::EOR,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::LSR_ZPX,  MetaOp::LSR,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::CLI_IMP,  MetaOp::CLI,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::EOR_ABY,  MetaOp::EOR,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::EOR_ABX,  MetaOp::EOR,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::LSR_ABX,  MetaOp::LSR,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::RTS_IMP,  MetaOp::RTS,  AddrMode::IMP, true , None                   ),
	InstDesc::new(Opcode::ADC_IZX,  MetaOp::ADC,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::ADC_ZPG,  MetaOp::ADC,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::ROR_ZPG,  MetaOp::ROR,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(Opcode::PLA_IMP,  MetaOp::PLA,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::ADC_IMM,  MetaOp::ADC,  AddrMode::IMM, false, None                   ),
	InstDesc::new(Opcode::ROR_IMP,  MetaOp::RORA, AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::JMP_IND,  MetaOp::JMP,  AddrMode::IND, true,  Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::ADC_ABS,  MetaOp::ADC,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::ROR_ABS,  MetaOp::ROR,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::BVS_REL,  MetaOp::BVS,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(Opcode::ADC_IZY,  MetaOp::ADC,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::ADC_ZPX,  MetaOp::ADC,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::ROR_ZPX,  MetaOp::ROR,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::SEI_IMP,  MetaOp::SEI,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::ADC_ABY,  MetaOp::ADC,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::ADC_ABX,  MetaOp::ADC,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::ROR_ABX,  MetaOp::ROR,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::STA_IZX,  MetaOp::STA,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::STY_ZPG,  MetaOp::STY,  AddrMode::ZPG, false, Some(MemAccess::Write) ),
	InstDesc::new(Opcode::STA_ZPG,  MetaOp::STA,  AddrMode::ZPG, false, Some(MemAccess::Write) ),
	InstDesc::new(Opcode::STX_ZPG,  MetaOp::STX,  AddrMode::ZPG, false, Some(MemAccess::Write) ),
	InstDesc::new(Opcode::DEY_IMP,  MetaOp::DEY,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::TXA_IMP,  MetaOp::TXA,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::STY_ABS,  MetaOp::STY,  AddrMode::ABS, false, Some(MemAccess::Write) ),
	InstDesc::new(Opcode::STA_ABS,  MetaOp::STA,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::STX_ABS,  MetaOp::STX,  AddrMode::ABS, false, Some(MemAccess::Write) ),
	InstDesc::new(Opcode::BCC_REL,  MetaOp::BCC,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(Opcode::STA_IZY,  MetaOp::STA,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::STY_ZPX,  MetaOp::STY,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::STA_ZPX,  MetaOp::STA,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::STX_ZPY,  MetaOp::STX,  AddrMode::ZPY, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::TYA_IMP,  MetaOp::TYA,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::STA_ABY,  MetaOp::STA,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::TXS_IMP,  MetaOp::TXS,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::STA_ABX,  MetaOp::STA,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::LDY_IMM,  MetaOp::LDYI, AddrMode::IMM, false, None                   ),
	InstDesc::new(Opcode::LDA_IZX,  MetaOp::LDA,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::LDX_IMM,  MetaOp::LDXI, AddrMode::IMM, false, None                   ),
	InstDesc::new(Opcode::LDY_ZPG,  MetaOp::LDY,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::LDA_ZPG,  MetaOp::LDA,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::LDX_ZPG,  MetaOp::LDX,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::TAY_IMP,  MetaOp::TAY,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::LDA_IMM,  MetaOp::LDAI, AddrMode::IMM, false, None                   ),
	InstDesc::new(Opcode::TAX_IMP,  MetaOp::TAX,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::LDY_ABS,  MetaOp::LDY,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::LDA_ABS,  MetaOp::LDA,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::LDX_ABS,  MetaOp::LDX,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::BCS_REL,  MetaOp::BCS,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(Opcode::LDA_IZY,  MetaOp::LDA,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::LDY_ZPX,  MetaOp::LDY,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::LDA_ZPX,  MetaOp::LDA,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::LDX_ZPY,  MetaOp::LDX,  AddrMode::ZPY, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::CLV_IMP,  MetaOp::CLV,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::LDA_ABY,  MetaOp::LDA,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::TSX_IMP,  MetaOp::TSX,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::LDY_ABX,  MetaOp::LDY,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::LDA_ABX,  MetaOp::LDA,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::LDX_ABY,  MetaOp::LDX,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::CPY_IMM,  MetaOp::CPY,  AddrMode::IMM, false, None                   ),
	InstDesc::new(Opcode::CMP_IZX,  MetaOp::CMP,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::CPY_ZPG,  MetaOp::CPY,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::CMP_ZPG,  MetaOp::CMP,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::DEC_ZPG,  MetaOp::DEC,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(Opcode::INY_IMP,  MetaOp::INY,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::CMP_IMM,  MetaOp::CMP,  AddrMode::IMM, false, None                   ),
	InstDesc::new(Opcode::DEX_IMP,  MetaOp::DEX,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::CPY_ABS,  MetaOp::CPY,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::CMP_ABS,  MetaOp::CMP,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::DEC_ABS,  MetaOp::DEC,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::BNE_REL,  MetaOp::BNE,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(Opcode::CMP_IZY,  MetaOp::CMP,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::CMP_ZPX,  MetaOp::CMP,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::DEC_ZPX,  MetaOp::DEC,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::CLD_IMP,  MetaOp::CLD,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::CMP_ABY,  MetaOp::CMP,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::CMP_ABX,  MetaOp::CMP,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::DEC_ABX,  MetaOp::DEC,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::CPX_IMM,  MetaOp::CPX,  AddrMode::IMM, false, None                   ),
	InstDesc::new(Opcode::SBC_IZX,  MetaOp::SBC,  AddrMode::IZX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::CPX_ZPG,  MetaOp::CPX,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::SBC_ZPG,  MetaOp::SBC,  AddrMode::ZPG, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::INC_ZPG,  MetaOp::INC,  AddrMode::ZPG, false, Some(MemAccess::Rmw)   ),
	InstDesc::new(Opcode::INX_IMP,  MetaOp::INX,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::SBC_IMM,  MetaOp::SBC,  AddrMode::IMM, false, None                   ),
	InstDesc::new(Opcode::NOP_IMP,  MetaOp::NOP,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::CPX_ABS,  MetaOp::CPX,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::SBC_ABS,  MetaOp::SBC,  AddrMode::ABS, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::INC_ABS,  MetaOp::INC,  AddrMode::ABS, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::BEQ_REL,  MetaOp::BEQ,  AddrMode::REL, true,  Some(MemAccess::Target)),
	InstDesc::new(Opcode::SBC_IZY,  MetaOp::SBC,  AddrMode::IZY, false, Some(MemAccess::Read)  ),
	InstDesc::new(Opcode::SBC_ZPX,  MetaOp::SBC,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::INC_ZPX,  MetaOp::INC,  AddrMode::ZPX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::SED_IMP,  MetaOp::SED,  AddrMode::IMP, false, None                   ),
	InstDesc::new(Opcode::SBC_ABY,  MetaOp::SBC,  AddrMode::ABY, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::SBC_ABX,  MetaOp::SBC,  AddrMode::ABX, false, Some(MemAccess::Offset)),
	InstDesc::new(Opcode::INC_ABX,  MetaOp::INC,  AddrMode::ABX, false, Some(MemAccess::Offset)),
];